### ISSUE TITLE
Incompatible with react-ladda

### ISSUE THREAD

**Issue by paddycarver** [shatran/card-react#1]
When attempting to use this library with [react-ladda](https://github.com/jsdir/react-ladda), react-ladda breaks with the message:

`Uncaught TypeError: Cannot read property 'hasOwnProperty' of undefined`

This points to [line 73](https://github.com/jsdir/react-ladda/blob/v2.0.4/index.js#L73) of react-ladda. So far, this is the only library I've used that has broken react-ladda, so I figure it has something to do with the fact that this isn't a pure react library, but a wrapper around something that mutates the DOM. The crux of the problem is that the `<button>` element inside the `<LaddaButton>` element does not seem to be an object? But this works when not using card-react.

**Comment by shatran** [comment]
card-react is a react library and does not mutates the DOM like jQuery etc - It does all of its changes by re rendering the form and the card elements. regarding your error - in line 73 of react-ladda, the code is trying to use React.addons.cloneWithProps which is deprecated according to [React Docs](https://facebook.github.io/react/docs/clone-with-props.html). In card-react the form elements are also being cloned so maybe the different clone methods used cause the problem. maybe you can provide the code so i can take a look at it?
