### ISSUE TITLE
Payment.js is still used as pre-built instead of source (?)

### ISSUE THREAD

**Issue by harel** [shatran/card-react#10]
I know there was a previous ticket, and it was meant to have been solved, but using the latest card-react from npm, in a webpack setup, I'm getting this: 

`
WARNING in ./~/card-react/~/payment/lib/payment.js
Critical dependencies:
1:505-512 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/card-react/~/payment/lib/payment.js 1:505-512
`

When npm starts/reloads. 

I thought this was resolved last year already?

**Comment by shatran** [comment]
No it wasn't resolved fully for both we pack and non we pack users. If you have a solution your more then welcome to submit a PR for handling this.

**Comment by harel** [comment]
I wonder if its because you're using an old version of payment.js (which is in 1.0.4 at the moment).

**Comment by shatran** [comment]
According to this jessepollak/payment#15 it's not resolved yet in payment and probably will be resolved in the next version.

**Comment by harel** [comment]
Yep, that makes sense. Thanks. I'll wait for them to resolve it then.

**Comment by harel** [comment]
Payment.js seem to have pushed v2 beta which allegedly fixes that issue. Though I suspect it will require you to update your packages to use that version.

**Comment by shatran** [comment]
Hi, just pushed v 1.2.1 It includes payment 2.0.3. Hope it will fix your issue

**Comment by harel** [comment]
Thanks dude!

**Comment by harel** [comment]
Works a treat. Any chance of updating npm to make it official?
