### ISSUE TITLE
npm run fails requiring global ruby/sass

### ISSUE THREAD

**Issue by samsch** [shatran/card-react#18]
I cloned the repo, then ran `npm install` and `npm run`. Running fails at:

```
Running "sass:dist" (sass) task
Warning: 
You need to have Ruby and Sass installed and in your PATH for this task to work.
More info: https://github.com/gruntjs/grunt-contrib-sass
 Use --force to continue.

Aborted due to warnings.
```

Maybe the solution here would be to drop ruby/sass in favour of installing node sass as a dev dependency.

**Comment by shatran** [comment]
Its a good idea, You are more then welcome to submit a PR.

**Comment by samsch** [comment]
I didn't end up using card-react due to this problem, and I have no experience with grunt (nor a reason to get started with it). I won't be able to implement this for you.
