### ISSUE TITLE
is there a way to separate out the expiration fields? 

### ISSUE THREAD

**Issue by amit-coditas** [shatran/card-react#20]
i am integrating this with stripe, and it requires the expiration fields to be separate like one input field for month and one for year.

**Comment by mmcnellis** [comment]
amit-coditas, I thought that was the case at first when looking at their documentation; however, Stripe does not actually require that. I currently have it working with just one MM/YYYY expiry field like so:

`var stripeData = {number: this.state.number,exp: this.state.exp,cvc: this.state.cvc,name: this.state.name}
`
`Stripe.createToken(stripeData, function (status, response) { ... }
`
