### ISSUE TITLE
Entering every 4th digit doesn't trigger onChange

### ISSUE THREAD

**Issue by mmcnellis** [shatran/card-react#21]
Due to
 `Payment.formatCardNumber ReactDOM.findDOMNode(@refs[@inputsRefs[inputsNames["number"]]])
`
the DOM is directly manipulated on every 4th digit entry, and thus card data cannot be saved to state using onChange events.

**Comment by ferenckv** [comment]
I'm having this very same issue but only when using redux-forms.

**Comment by Stas-Buzunko** [comment]
Hi, the same issue, have you found a way to fix it?

**Comment by ferenckv** [comment]
It looks like an issue with paymentjs and React:  https://github.com/jessepollak/payment/issues/53

**Comment by mmcnellis** [comment]
@ferenckv @Stas-Buzunko I came up with a working solution the other day: https://github.com/mmcnellis/card-react/commit/1c416aadbce29cb810f56d5039214847287e411d

Just add a function in the parent component that updates card number in state, and pass it as the updateNumber prop. Works like a charm

**Comment by AlexGaspar** [comment]
If we trigger `input` instead of `change` [here](https://github.com/jessepollak/payment/blob/master/src/index.coffee#L173-L183) and allow it to bubble up, it triggers the onChange handler (at least in my case).

```coffee
  QJ.trigger(target, 'change')
```
Into:
```coffee
  target.dispatchEvent new Event('input', bubbles: true)
```

@mmcnellis, @ferenckv: does that work for you?

**Comment by shatran** [comment]
I'll wait for a development on the card.js front. Maybe they will find a solution for that.

**Comment by JesperWe** [comment]
Thanks for the workaround to this annoying bug, @mmcnellis! (Although I prefer to pass the whole `event` instead of the value to use the same handler as for onChange)

**Comment by shatran** [comment]
Is this issue solved with the new version?
