### ISSUE TITLE
initialValues don't re-render

### ISSUE THREAD

**Issue by Stas-Buzunko** [shatran/card-react#22]
Some users have already filled card info, in this case I have to fetch their data to let them edit it. So when it renders for the first time it uses default values. Then when data is fetched it appears in inputs but card display doesn't re-render with new values, and it re-renders only if input value is changed.

How can I fix this?

**Comment by shatran** [comment]
I guess you should only render the card when you have the fetched values? closing it as this is not an issue.

**Comment by shatran** [comment]
I guess you should only render the card when you have the fetched values?
