### ISSUE TITLE
Incomplete event handling missing input fill in from browser suggestion popup

### ISSUE THREAD

**Issue by JesperWe** [shatran/card-react#24]
Thanks for a nice React-ification of Card, better integrated than others!

The current setup of event handles (onKeyUp, onBlur) for validation misses the case when:

- the user has previously filled out the form
- has the browser set to remember filled in values
-  double clicks the field and then selects the previous value from the browser popup

In this case neither of these event happen, even though the input has been filled in.

**Comment by shatran** [comment]
Hi @JesperWe. Thanks!. You are more then welcome to submit a PR with those features and we can think about integrating them. Thanks again.

**Comment by shatran** [comment]
close since this is future improvement and not an issue
