### ISSUE TITLE
HTML encoding for default values that include '••••' is not working for React ^0.14.3

### ISSUE THREAD

**Issue by sstern6** [shatran/card-react#6]
On page load with given default values from /lib/card-react-component.js is having trouble encoding the proper values that were intended to be there, mainly with the bullet points for the CC default values.

This is what it is returning on the browser:

https://cloud.githubusercontent.com/assets/10355544/12796608/7cba4774-ca74-11e5-941e-e4f5c6f83bc2.png

I am not sure if this is just happening on my machine but I would be more than happy to make a PR to fix this issue.  I worked in basic JS into one of the lib files which seemed to fix the issue, returning this to the browser.  I believe this is happening because some HTML encoding isnt supporting the • on page render.

https://cloud.githubusercontent.com/assets/10355544/12796692/e2f3de7e-ca74-11e5-9d09-2fadb42deb8c.png

@shatran thoughts?

Thank you

**Comment by shatran** [comment]
Hi @sstern6, I haven't encountered this issue yet. card-react doesn't currently supports React ^0.14 (doesn't use ReactDOM) and that might be one possible reason for your problem (although it's not necessarily related). 
If you have a solution that worked for you please send a PR and i'll take a look at it.

**Comment by sstern6** [comment]
@shatran ok thanks.  Its a simple solution, using String.charcode instead of the dot. 

I will submit a PR tonight, I would like to hear your thought!

Thank you

**Comment by shatran** [comment]
It now on version 1.1.20. let me know if it works for you

**Comment by sstern6** [comment]
@shatran PERFECT. I will implement and let you know how it goes!
