### ISSUE TITLE
How to get input values?

### ISSUE THREAD

**Issue by rmdydo** [shatran/card-react#8]
I am brand new to react and I am having difficulty getting the values of the form inputs. It appears that adding onChange events to the inputs interferes with the credit card component. What is the recommended way to get the values of the inputs?
Thanks

**Comment by shatran** [comment]
Hi @rmdydo,
The card component listens to onKeyUp, onFocus and onBlur, so it shouldn't interfere with the onChange event of the input fields. Can you elaborate more about your problem?

**Comment by rmdydo** [comment]
I was able to figure it out using refs: https://facebook.github.io/react/docs/more-about-refs.html#the-ref-string-attribute
Thanks
